### ISSUE TITLE
Ошибка в консоле - не может найти файл по текущему пути

### ISSUE THREAD

**Issue by igosheva** [maxmjr/maxmjr.github.io#1]
https://github.com/maxmjr/maxmjr.github.io/blob/70bbf0b460c13fc2ae892a94cb3e2a723948fdd4/index.html#L44

**Comment by maxmjr** [comment]
убрал название папки, класса, картинки banner (адблок таргетно блокирует по именам классов, названий картинок и т.п.), заменил на promotion
