### ISSUE TITLE
Ошибка в нейминге. Имена элементов пишутся через два нижних подчеркивания( featrues__image), а имена модификаторов пишутся как имя элемента--модификатор (featrues__image--unique)

### ISSUE THREAD

**Issue by igosheva** [maxmjr/maxmjr.github.io#3]
https://github.com/maxmjr/maxmjr.github.io/blob/70bbf0b460c13fc2ae892a94cb3e2a723948fdd4/index.html#L56

**Comment by maxmjr** [comment]
отредактировал следуя правилам бэм-нейминга
features__image -> features__image
image--unique -> features__image--unique
image--premium-class -> features__image--premium-class
image--personal-trainer -> featrues__image--personal-trainer
