### ISSUE TITLE
Ошибка в нейминге. Класс с модификатором не может идти без основного класса.

### ISSUE THREAD

**Issue by igosheva** [maxmjr/maxmjr.github.io#5]
https://github.com/maxmjr/maxmjr.github.io/blob/70bbf0b460c13fc2ae892a94cb3e2a723948fdd4/index.html#L59

**Comment by maxmjr** [comment]
убрал модификатор, он тут не нужен

<ul class="features__list--container">  -> <ul class="features__list">
