### ISSUE TITLE
Ошибка в нейминге у всех внутренних элементов. Класс с модификатором не может идти без основного класса.

### ISSUE THREAD

**Issue by igosheva** [maxmjr/maxmjr.github.io#7]
https://github.com/maxmjr/maxmjr.github.io/blob/70bbf0b460c13fc2ae892a94cb3e2a723948fdd4/index.html#L99

**Comment by maxmjr** [comment]
<div class="news__content news__content--prop"> -> <div class="news__content">

убрал лишний класс с модификатором, он тут попросту не нужен
